namespace TallyG.Tax.Api.Modules.Accounting;

/// <summary>
/// Central policy for the " (E)" trace mark on system-generated ledgers. The mark is a human-visible
/// signal in the ledger name; the structural source of truth is <c>Ledger.IsSystemGenerated</c>.
/// Keeping the suffix here means the matcher, the poster and the chart-of-accounts editor all agree
/// on exactly one form.
/// </summary>
public static class LedgerNaming
{
    /// <summary>The suffix appended to auto-created account heads (E = generated by the Engine).</summary>
    public const string GeneratedSuffix = " (E)";

    /// <summary>Append the trace mark if it is not already present.</summary>
    public static string Mark(string baseName)
    {
        var name = (baseName ?? string.Empty).Trim();
        return IsMarked(name) ? name : name + GeneratedSuffix;
    }

    /// <summary>True if a name already carries the trace mark.</summary>
    public static bool IsMarked(string? name)
        => !string.IsNullOrWhiteSpace(name)
           && name.TrimEnd().EndsWith(GeneratedSuffix.Trim(), StringComparison.OrdinalIgnoreCase);

    /// <summary>The base name with any trailing trace mark removed (for matching/comparison).</summary>
    public static string Strip(string? name)
    {
        var n = (name ?? string.Empty).Trim();
        if (n.EndsWith(GeneratedSuffix.Trim(), StringComparison.OrdinalIgnoreCase))
        {
            n = n[..^GeneratedSuffix.Trim().Length].TrimEnd();
        }

        return n;
    }
}
